version: '3'

services:
  react-spotify:
    container_name: react-spotify
    image: tazoo/react-spotify
    build: 
      context: .
      dockerfile: Dockerfile
    # environment:
      # NODE_ENV: production
    ports:
      - "3000:3000"
      - "8888:8888"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules