version: '3'

services:
  react-spotify:
    container_name: react-spotify
    image: tazoo/react-spotify
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules